version: "3"
services:

  redis:
    image: redis:3.2
    command: redis-server --appendonly yes --requirepass 269f7df4-4cf3-4b2f-8e33-53ed126d4cd1
    volumes:
      - "${HOST_PATH}/redis:/data"
    ports:
      - "6379:6379"
        
  atlas-A1:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=0?ServerY=0?AltSaveDirectoryName=A1?QueryPort=57500?Port=5700?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
      - "57500:57500/udp"
      - "5700:5700/udp"
      - "27000:27000"
    volumes:
      - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
      - redis
    
  atlas-B1:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=1?ServerY=0?AltSaveDirectoryName=B1?QueryPort=57510?Port=5710?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
      - "57510:57510/udp"
      - "5710:5710/udp"
      - "27010:27010"
    volumes:
      - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
      - redis
    
  atlas-C1:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=2?ServerY=0?AltSaveDirectoryName=C1?QueryPort=57520?Port=5720?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
      - "57520:57520/udp"
      - "5720:5720/udp"
      - "27020:27020"
    volumes:
      - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
      - redis
    
  atlas-D1:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=3?ServerY=0?AltSaveDirectoryName=D1?QueryPort=57530?Port=5730?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
      - "57530:57530/udp"
      - "5730:5730/udp"
      - "27030:27030"
    volumes:
      - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
      - redis
    
  atlas-A2:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=0?ServerY=1?AltSaveDirectoryName=A2?QueryPort=57501?Port=5701?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
      - "57501:57501/udp"
      - "5701:5701/udp"
      - "27001:27001"
    volumes:
      - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
      - redis
    
  atlas-B2:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=1?ServerY=1?AltSaveDirectoryName=B2?QueryPort=57511?Port=5711?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
      - "57511:57511/udp"
      - "5711:5711/udp"
      - "27011:27011"
    volumes:
      - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
      - redis
    
  atlas-C2:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=2?ServerY=1?AltSaveDirectoryName=C2?QueryPort=57521?Port=5721?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
      - "57521:57521/udp"
      - "5721:5721/udp"
      - "27021:27021"
    volumes:
      - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
      - redis
    
  atlas-D2:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=3?ServerY=1?AltSaveDirectoryName=D2?QueryPort=57531?Port=5731?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
      - "57531:57531/udp"
      - "5731:5731/udp"
      - "27031:27031"
    volumes:
      - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
      - redis
    
  atlas-A3-homeserver:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=0?ServerY=2?AltSaveDirectoryName=A3?QueryPort=57502?Port=5702?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
    - "57502:57502/udp"
    - "5702:5702/udp"
    - "27002:27002"
    volumes:
    - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
    - redis

  atlas-B3:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=0?ServerY=2?AltSaveDirectoryName=B3?QueryPort=57512?Port=5712?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
    - "57512:57512/udp"
    - "5712:5712/udp"
    - "27012:27012"
    volumes:
    - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
    - redis

  atlas-C3:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=0?ServerY=2?AltSaveDirectoryName=C3?QueryPort=57522?Port=5722?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
    - "57522:57522/udp"
    - "5722:5722/udp"
    - "27022:27022"
    volumes:
    - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
    - redis

  atlas-D3:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=0?ServerY=2?AltSaveDirectoryName=D3?QueryPort=57532?Port=5732?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
    - "57532:57532/udp"
    - "5732:5732/udp"
    - "27032:27032"
    volumes:
    - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
    - redis

  atlas-A4:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=0?ServerY=2?AltSaveDirectoryName=A4?QueryPort=57503?Port=5703?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
    - "57503:57503/udp"
    - "5703:5703/udp"
    - "27003:27003"
    volumes:
    - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
    - redis


  atlas-B4:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=0?ServerY=2?AltSaveDirectoryName=B4?QueryPort=57503?Port=5703?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
    - "57513:57513/udp"
    - "5713:5713/udp"
    - "27013:27013"
    volumes:
    - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
    - redis

  atlas-C4:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=0?ServerY=2?AltSaveDirectoryName=C4?QueryPort=57503?Port=5703?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
    - "57523:57523/udp"
    - "5723:5723/udp"
    - "27023:27023"
    volumes:
    - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
    - redis

  atlas-D4:
    image: atlas-server
    tty: true
    command: start-server "Ocean?ServerX=0?ServerY=2?AltSaveDirectoryName=D4?QueryPort=57503?Port=5703?MaxPlayers=${MAX_PLAYERS}?ReservedPlayerSlots=${RESERVED_PLAYERS}?SeamlessIP=${EXTERNAL_IP} -NoBattlEye -log -server"
    ports:
    - "57533:57533/udp"
    - "5733:5733/udp"
    - "27033:27033"
    volumes:
    - "${HOST_PATH}:/mnt/atlas-server/"
    depends_on:
    - redis
